<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Lyra.API</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Lyra.Application/Lyra.Application.csproj" />
    <ProjectReference Include="../Lyra.Infrastructure/Lyra.Infrastructure.csproj" />
    <ProjectReference Include="../Lyra.Core/Lyra.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
</Project>
